version: '3'
services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    container_name: derma_thesis
    image: derma_thesis
    init: true
    volumes:
      - ..:/DERMA-THESIS:cached